/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */
group = "speculator.cli.test"
version = "1.0.0"

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // id("com.github.mrsarm.jshell.plugin") version "1.2.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(platform("ai.djl:bom:0.36.0"))
    // implementation("ai.djl.android:core")
    // runtimeOnly("ai.djl.android:pytorch-native")
    // runtimeOnly("ai.djl.android:onnxruntime")
    implementation("speculator.engine:lib:1.0.0")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

application {
    // Define the main class for the application.
    mainClass = "org.example.Main"
}
