/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Duration;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.stream.Collector;
import java.util.stream.Collectors;

import javax.management.RuntimeErrorException;

import org.example.startupScripts.TestScript1;
import org.example.startupScripts.TestScript2;
import org.example.startupScripts.TestScript3;
import org.example.startupScripts.TestScript4;

import engine.Serialisation.EditMenu;
import engine.Serialisation.Menu;
import engine.control.App;
import engine.menus.Tickers;

public class Main{
    private static Consumer<List<String>> INVALID = cmd -> System.out.println("invalid command");
    
    private static String prompt = "Speculator >>>";
    private static String errorMessage = "Bad arguments:";
    private static List<String> parseCommand(String command) {
        command = command + " ";
        List<String> args = new ArrayList<>();
        StringBuilder word = new StringBuilder();
        boolean escape = false;
        for (char c : command.toCharArray()) {
            if (escape) {
                if (c == '\"') {
                    escape = false;
                    args.add(word.toString());
                    word = new StringBuilder();
                } else {
                    word.append(c);
                }

            } else {
                if (c == ' ' || c == '\n') {
                    if (word.length() > 0) {
                        args.add(word.toString());
                        word = new StringBuilder();
                    }
                } else if (c == '\"') {
                    escape = true;
                } else {
                    word.append(c);
                }
            }
        }
        return args;
    }
    private static void list(List<?> items) {
        StringBuilder res = new StringBuilder();
        for (int i = 0; i < items.size(); i++) {
            res.append(i + ":: " + items.get(i) + '\n');
        }
        System.out.println(res.toString());
    }
    private static Consumer<List<String>> dispatch(Map<String, Consumer<List<String>>> funcs) {
        return command -> {
            if (command.isEmpty() || !funcs.containsKey(command.get(0))) {
                funcs.getOrDefault("", INVALID).accept(command.subList(0, command.size()));
            } else {
                funcs.getOrDefault(command.get(0), INVALID).accept(command.subList(1, command.size()));
            }
        };
    }
    private static Consumer<List<String>> dispatchMenu(Menu<?> menu) {
        return dispatch(Map.of(
            "ls", cmd -> {
                Set<Integer> selected = menu.getSelectedIndices();
                List<String> labels = menu.getLabels();
                List<String> res = new ArrayList();
                for (int i = 0; i<labels.size(); i++) {
                    if (selected.contains(i)) {
                        res.add(labels.get(i) + " (selected)");
                    } else {
                        res.add(labels.get(i));
                    }
                }
                list(res);
            },
            "sel", cmd -> menu.selectAll(cmd.stream().map(Integer::parseInt).collect(Collectors.toList())),
            "usel", dispatch(Map.of(
                "", cmd -> cmd.stream().map(Integer::parseInt).forEach(menu::unselect),
                "a", cmd -> menu.unselectAll()
            ))
        ));
    }
    private App app;
    private Map<String, Consumer<List<String>>> commands;
    private Map<EditMenu<?>, Map<String, String>> savedConfigs = new HashMap<>();
    private boolean agentActive = false;
    
    private Consumer<List<String>> dispatchEditMenu(EditMenu<?> menu) {
        return dispatch(Map.of(
            "", dispatchMenu(menu),
            "base", dispatch(Map.of(
                "ls", cmd -> {
                    int selected = menu.selectedLoaderIndex();
                    List<String> labels = menu.loaders();
                    List<String> res = new ArrayList();
                    for (int i = 0; i<labels.size(); i++) {
                        if (selected == i) {
                            res.add(labels.get(i) + " (selected)");
                        } else {
                            res.add(labels.get(i));
                        }
                    }
                list(res);
                },
                "sel", cmd -> {
                    menu.selectLoader(Integer.parseInt(cmd.get(0)));
                    savedConfigs.put(menu, menu.getOptions().stream().collect(Collectors.toMap(opt -> opt, opt -> "")));
                }
            )),
            "mk", cmd -> {
                menu.add(savedConfigs.get(menu));
            },
            "rm", cmd -> {
                menu.remove(cmd.stream().map(Integer::parseInt).collect(Collectors.toList()));
            },
            "conf", dispatch(Map.of(
                "", cmd -> {
                    if (! savedConfigs.containsKey(menu)) {
                        savedConfigs.put(menu, menu.getOptions().stream().collect(Collectors.toMap(opt -> opt, opt -> "")));
                    }
                    savedConfigs.get(menu).put(menu.getOptions().get(Integer.parseInt(cmd.get(0))), cmd.get(1));
                },
                "ls", cmd -> {
                    list(menu.getOptions().stream().map(opt -> opt + ": " + savedConfigs.getOrDefault(menu, Map.of()).getOrDefault(opt, "(empty)")).collect(Collectors.toList()));
                }
            ))

        ));
    }

    public Main(Path root, boolean reset) {
        if (reset) {
            app = App.startNew(root, new TestReporter(), new TestDrawer());
        } else {
            app = App.start(root, new TestReporter(), new TestDrawer());
            
        }
        initCommands();
    }
    public Main(Path root, boolean reset, StartupScript script) {
        this(root, reset);
        script.onStartUp(this);
    }
    private void initCommands() {
        commands = new HashMap<>();
        commands.putAll(Map.of(
            "exit", args -> {
                app.save();
                System.out.println("---/ Speculator CLI (test) ---");
            },
            "auth", dispatch(Map.of(
                "", cmd -> {
                    String field = app.getAuthFields().get(Integer.parseInt(cmd.get(0)));
                    String cred = cmd.get(1);
                    app.authenticate(Map.of(field, cred));
                },
                "ls", dispatch(Map.of(
                    "", cmd -> list(app.getAuthFields().stream().map(f -> f+(app.isAuthFilled(f) ? " (filled)"  : " (empty)")).collect(Collectors.toList()))
                ))
            )),
            "tic", dispatchMenu(app.getTickers()),
            "ups", dispatchMenu(app.getUpstreams()),
            "plt", dispatchMenu(app.getPlotters()),
            "exe", dispatchMenu(app.getExecutors()),
            "mod", dispatchEditMenu(app.getModels()),
            "pre", dispatchEditMenu(app.getPresets()),
            "agt", dispatch(Map.of(
                "", dispatchEditMenu(app.getAgents()),
                "on", cmd -> {
                    agentActive = true;
                },
                "off", cmd -> {
                    agentActive = false;
                }

            )),
            "pull", dispatch(Map.of(
                "", cmd -> {
                app.pullPlot(Duration.ofHours(Long.parseLong(cmd.get(0)))
                    .plusMinutes(Long.parseLong(cmd.get(1)))
                    .plusSeconds(Long.parseLong(cmd.get(2))));
                },
                "loop", cmd -> app.pullPlotCycle(Duration.ofHours(Long.parseLong(cmd.get(0)))
                    .plusMinutes(Long.parseLong(cmd.get(1)))
                    .plusSeconds(Long.parseLong(cmd.get(2)))
                )
            )) 

        ));
        commands.putAll(Map.of(
            "btst", cmd -> {
                ZonedDateTime at = ZonedDateTime.of(
                    Integer.parseInt(cmd.get(0)),
                    Integer.parseInt(cmd.get(1)),
                    Integer.parseInt(cmd.get(2)),
                    Integer.parseInt(cmd.get(3)),
                    0, 0, 0, ZoneId.systemDefault()
                );
                if (agentActive) {
                    app.backtestAct(at);
                } else {
                    app.backtestPredict(at);
                }
            },
            "pred", dispatch(Map.of(
                "", cmd -> {
                    if (agentActive) {
                        app.predictAct();
                    } else {
                        app.predictPlot();
                    }
                },
                "loop", cmd -> {
                    if (agentActive) {
                        app.predictActCycle(Duration.ofSeconds(Long.parseLong(cmd.get(0))));
                    } else {
                        app.predictPlotCycle();
                    }
                }
            )) ,
            "sim", dispatch(Map.of(
                "", cmd -> {
                    ZonedDateTime start = ZonedDateTime.now().minus(Duration.ofHours(Long.parseLong(cmd.get(0))));
                    ZonedDateTime end = ZonedDateTime.now().minus(Duration.ofHours(Long.parseLong(cmd.get(1))));
                    Duration step = Duration.ofSeconds(Long.parseLong(cmd.get(2)));
                    app.simulate(
                        start,
                        end,
                        step
                    );
                },
                "loop", cmd -> {
                    app.simulateCycle(Duration.ofSeconds(Long.parseLong(cmd.get(0))));
                }
            )),
            "_f", cmd -> app.completeTasks() ,
            "stop", cmd -> app.endTasks()
        ));
    }

    private void mainLoop() {
        Scanner scanner = new Scanner(System.in);
        while (true) {
            System.out.print(prompt);
            List<String> command = parseCommand(scanner.nextLine());
            try{
                dispatch(commands).accept(command);
            } catch (RuntimeException e) {
                System.out.println(errorMessage);
                e.printStackTrace(System.out);
            }
            if (command.get(0).equals("exit")) {
                break;
            }
        }
        scanner.close();
        System.exit(0);
    }

    public void run(String command) {
        dispatch(commands).accept(parseCommand(command));
    }

    public static void main(String[] args) {
        // Main app = new Main(Path.of(".live"), false, new TestScript3());
        // Main app = new Main(Path.of(".live"), true, new TestScript1());
        Main app = new Main(Path.of(".live"), false);
        
        if (args.length > 0) {
            try {
                Files.readAllLines(Paths.get(args[0])).stream()
                    .map(Main::parseCommand)
                    .forEach(cmd -> dispatch(app.commands).accept(cmd));
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

        System.out.println("--- Speculator CLI (test) ---");
        app.mainLoop();
    }

}
