/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.stream.Collectors;

import engine.control.App;

public class Main{
    private static Consumer<List<String>> INVALID = cmd -> System.out.println("invalid command");
    private static String prompt = "Speculator >>>";
    private static String errorMessage = "Bad arguments:";
    private static Consumer<List<String>> dispatch(Map<String, Consumer<List<String>>> funcs) {
        return command -> {
            if (command.isEmpty() || !funcs.containsKey(command.get(0))) {
                funcs.getOrDefault("", INVALID).accept(command.subList(0, command.size()));
            } else {
                funcs.getOrDefault(command.get(0), INVALID).accept(command.subList(1, command.size()));
            }
        };
    }
    private App app;
    private Map<String, Consumer<List<String>>> commands = Map.of(
        "exit", args -> app.save(),
        "auth", dispatch(Map.of(
                "", cmd -> {
                    String field = cmd.get(0);
                    String cred = cmd.get(1);
                    System.out.println("bug start: "+ field + " " + cred);
                    app.authenticate(Map.of(field, cred));
                },
                "list", dispatch(Map.of(
                    "", cmd -> {
                        StringBuilder res = new StringBuilder();
                        app.getAuthFields().stream()
                            .peek(res::append)
                            .peek(field -> {
                                if (app.isAuthFilled(field)) {
                                    res.append(" (filled)");
                                } else {
                                    res.append(" (empty)");
                                }
                            })
                            .forEach(field -> res.append(", "));
                        System.out.println(res.toString());
                    }
                ))
            ))
        );
    public Main(Path root) {
        app = App.start(root, new TestReporter(), new TestDrawer());
    }
    private List<String> parseCommand(String command) {
        command = command + " ";
        List<String> args = new ArrayList<>();
        StringBuilder word = new StringBuilder();
        boolean escape = false;
        for (char c : command.toCharArray()) {
            if (escape) {
                if (c == '\"') {
                    escape = false;
                    args.add(word.toString());
                    word = new StringBuilder();
                } else {
                    word.append(c);
                }

            } else {
                if (c == ' ' || c == '\n') {
                    if (word.length() > 0) {
                        args.add(word.toString());
                        word = new StringBuilder();
                    }
                } else if (c == '\"') {
                    escape = true;
                } else {
                    word.append(c);
                }
            }
        }
        return args;
    }
    private void mainLoop() {
        Scanner scanner = new Scanner(System.in);
        while (true) {
            System.out.print(prompt);
            List<String> command = parseCommand(scanner.nextLine());
            try{
                dispatch(commands).accept(command);
            } catch (RuntimeException e) {
                System.out.println(errorMessage);
                e.printStackTrace(System.out);
            }
            if (command.get(0).equals("exit")) {
                break;
            }
        }
        scanner.close();
    }

    public static void main(String[] args) {
        Main app = new Main(Path.of(".live"));
        System.out.println("---Speculator CLI (test)---");
        app.mainLoop();
    }

}
